export const dynamic = 'force-dynamic';
import { setRequestLocale } from 'next-intl/server';
import { Metadata } from 'next';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  return {
    title: 'User Agreement | AI Generator',
    description: 'User Agreement and Terms of Service for AI Generator.',
  };
}

export default async function TermsOfServicePage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <main className="flex-1 container mx-auto max-w-4xl px-4 py-12 md:py-16">
        <article className="prose prose-slate dark:prose-invert max-w-none">
          <h1 className="text-3xl font-bold mb-8">User Agreement</h1>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">1. Introduction and Acceptance</h2>
            <p className="mb-2">
              1.1 Welcome to the "AI Generator" software and related services (collectively, the "Services") provided by Genea China Holdings Limited. and/or its affiliates (hereinafter referred to as "we," "us," or "AI Generator"). The Services refer to the products and services we provide through web pages, applications, mini-programs, APIs, SDKs, and other technological means, with generative AI interactive dialogue as the core function.
            </p>
            <p className="mb-2">
              1.2 Please read and fully understand all terms of this User Agreement (hereinafter referred to as "this Agreement") carefully before using the Services, paying particular attention to important clauses highlighted in bold or underlined, such as those on limitation of liability, intellectual property, and dispute resolution.
            </p>
            <p>
              1.3 If you do not agree to any provision of this Agreement, please stop accessing or using the Services immediately. Your act of registering, logging in, accessing, or continuing to use the Services signifies that you have read, understood, and agreed to be bound by this Agreement in its entirety. It also signifies your acceptance of our Privacy Policy and other relevant rules.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">2. Service Description and Important Notices</h2>
            <h3 className="text-lg font-medium mb-2">2.1 Nature and Limitations of the Service</h3>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>The Services provide content generation and information interaction functions based on generative artificial intelligence models and other technologies.</li>
              <li>All content generated by the Services (hereinafter referred to as "AI-Generated Content") is solely automated output based on algorithms and data and does not constitute professional advice of any form (including but not limited to advice in the fields of medical, legal, financial, or investment matters). AI-Generated Content may contain errors, inaccuracies, omissions, or be misleading, and may not reflect the latest information or policies. You bear full responsibility for referencing and using AI-Generated Content.</li>
            </ul>

            <h3 className="text-lg font-medium mb-2">2.2 Risk Notices for Specific Functions</h3>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li><strong>Health Consultation:</strong> Health-related responses provided by the Services do not constitute medical diagnosis, treatment advice, or electronic prescriptions and cannot replace the professional judgment of licensed medical practitioners. For health issues, you must consult qualified medical professionals and seek offline diagnosis and treatment.</li>
              <li><strong>Web Search:</strong> When the Services provide search results sourced from third-party web pages, such content is produced and provided by third parties. We only perform technical integration of the information and do not warrant or endorse its truthfulness, accuracy, or legality. You should exercise prudent judgment and verify such information independently.</li>
              <li><strong>Content Labeling:</strong> In accordance with the requirements of the "Interim Measures for the Management of Generative Artificial Intelligence Services" and other regulations, if AI-Generated Content may cause public confusion or misidentification, we will label it accordingly to the extent possible. You shall not remove or tamper with such labels.</li>
            </ul>
            <p>
              2.3 You understand and agree that, as necessary to provide the Services, you need to prepare your own terminal equipment and bear costs such as network communication fees. We reserve the right to adjust, update, or interrupt the service content, functions, or access methods based on business development, technological upgrades, or legal and regulatory requirements, and will provide advance notice to the extent possible.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">3. Account Registration and Management</h2>
            <p className="mb-2">3.1 The account you register is for your personal use only. You are legally responsible for all activities under your account (including consequences resulting from password disclosure).</p>
            <p className="mb-2">3.2 You must provide true, accurate, and complete registration information and update it promptly. We have the right to verify this information. If false information is discovered, we have the right to refuse or terminate the provision of services.</p>
            <p className="mb-2">3.3 <strong>Account Reclamation:</strong> If your account remains inactive (not logged into) for more than 6 months after registration, or if it poses risks as stipulated by laws and regulations, we have the right to reclaim the account. Before reclamation, we will notify you through reasonable means (e.g., in-app message, email).</p>
            <p>3.4 <strong>Account Deletion:</strong> You can apply to delete your account through the guidance within the application. Deletion is an irreversible operation that will result in the permanent loss of your account information, historical data, etc., except for records we are legally obligated to retain.</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">4. User Code of Conduct</h2>
            <p className="mb-2">4.1 You promise not to engage in the following activities when using the Services:</p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Inputting, generating, publishing, or disseminating any content that violates Chinese laws and regulations, the socialist system, national interests, or social morality, including but not limited to information related to terrorism, violence, pornography, gambling, fraud, or infringement of others' legitimate rights and interests (such as intellectual property, portrait rights, privacy rights).</li>
              <li>Using the Services to engage in any activity that undermines network security (e.g., hacking, spreading viruses, unauthorized data scraping).</li>
              <li>Interfering with or disrupting the normal operation of the Services in any way, or attempting to reverse engineer or decompile the Services.</li>
              <li>Using the Services for any scenario that may pose significant risks to persons or property (e.g., autonomous driving, medical diagnosis), or using AI-Generated Content for commercial decision-making, academic results, etc. without substantive human review.</li>
              <li>Impersonating others or compromising the security of others' accounts.</li>
            </ul>
            <p>4.2 If you violate the above provisions, we have the right to independently determine and take measures such as warning, restricting functions, suspending services, or terminating the account, and reserve the right to pursue legal liability.</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">5. Intellectual Property</h2>
            <p className="mb-2">5.1 <strong>Your Rights:</strong> Legitimate content you input into the Services ("Your Input") remains the intellectual property of you or the original rights holder.</p>
            <p className="mb-2">5.2 <strong>Our Rights:</strong> The software, technology, interface, logos, the "AI Generator" trademark, and related rights of the Services themselves are owned by us and our licensors. You may not use them without written permission.</p>
            <p className="mb-2">5.3 <strong>Ownership of AI-Generated Content:</strong> The intellectual property ownership of AI-Generated Content ("Output") produced in response to Your Input may be uncertain under current legal frameworks. We assert that, to the maximum extent permitted by law, you have the right to use the Output generated for your legitimate personal purposes. However, we provide no legal warranty regarding the ownership of the Output.</p>
            <p>5.4 <strong>License Grant:</strong> For the operation and improvement of the Services (including for model training), you grant us a worldwide, royalty-free license to use, store, and process Your Input and the corresponding Output. This license terminates after you delete the content or delete your account and after the necessary retention period in our systems ends.</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">6. Disclaimer and Limitation of Liability</h2>
            <p className="mb-2">6.1 We do not warrant that the Services will be uninterrupted, absolutely secure, or error-free. To the extent permitted by law, we are not liable for service issues caused by force majeure (e.g., natural disasters, policy changes), third-party actions, or existing technological limitations.</p>
            <p>6.2 In no event shall our aggregate liability to you for all claims exceed the total amount of fees you have directly paid to us for the Services giving rise to the claim (if any). We are not liable for any indirect, incidental, punitive, or consequential damages (such as loss of profits, data loss, or damage to goodwill).</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">7. Privacy Protection</h2>
            <p>We highly value the protection of your personal information. Please read and understand the Linked AI Privacy Policy in detail for information on how we collect, use, share, and protect your personal information. That policy forms an integral part of this Agreement.</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">8. Agreement Modification and Termination</h2>
            <p className="mb-2">8.1 We have the right to modify this Agreement based on changes in laws and regulations or business needs. After modification, we will publish the updated version on the relevant pages of the Services. If the changes materially affect your significant rights and interests, we will notify you through prominent means (e.g., push notification).</p>
            <p>8.2 Your continued use of the Services constitutes acceptance of the modified Agreement. If you do not agree to the modifications, you have the right to stop using the Services and apply to delete your account.</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">9. Governing Law and Dispute Resolution</h2>
            <p className="mb-2">9.1 The formation, validity, interpretation, performance, and dispute resolution of this Agreement shall be governed by the laws of HongKong SAR, China.</p>
            <p>9.2 Any dispute arising from or in connection with this Agreement shall first be resolved through friendly negotiation. If negotiation fails, you agree to submit the dispute to the competent people's court in the location of our company (HongKong SAR, China) for litigation.</p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4">10. Miscellaneous</h2>
            <p className="mb-2">10.1 If any provision of this Agreement is deemed invalid or unenforceable, the validity of the remaining provisions shall not be affected.</p>
            <p className="mb-2">10.2 Our failure or delay in exercising any right under this Agreement does not constitute a waiver of that right.</p>
            <p>10.3 If you have any questions, you can contact us through the feedback channel within the application or via email (tony@pregorange.com).</p>
          </section>
        </article>
      </main>
    </div>
  );
}